<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-03-12T20:04:45 IST" name="Suite" finished-at="2025-03-12T20:05:10 IST" duration-ms="24984">
    <groups>
    </groups>
    <test started-at="2025-03-12T20:04:45 IST" name="Test" finished-at="2025-03-12T20:05:10 IST" duration-ms="24984">
      <class name="com.orangehrm.tests.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.orangehrm.tests.LoginTest@402bba4f]" started-at="2025-03-12T20:04:46 IST" name="setUp" finished-at="2025-03-12T20:04:54 IST" duration-ms="8947" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testInvalidLogin()[pri:0, instance:com.orangehrm.tests.LoginTest@402bba4f]" started-at="2025-03-12T20:04:54 IST" name="testInvalidLogin" finished-at="2025-03-12T20:04:57 IST" duration-ms="2528" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.orangehrm.tests.LoginTest@402bba4f]" started-at="2025-03-12T20:04:57 IST" name="tearDown" finished-at="2025-03-12T20:04:57 IST" duration-ms="236" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.orangehrm.tests.LoginTest@402bba4f]" started-at="2025-03-12T20:04:57 IST" name="setUp" finished-at="2025-03-12T20:05:01 IST" duration-ms="3918" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testValidLogin()[pri:0, instance:com.orangehrm.tests.LoginTest@402bba4f]" started-at="2025-03-12T20:05:01 IST" name="testValidLogin" finished-at="2025-03-12T20:05:05 IST" duration-ms="3669" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.orangehrm.tests.LoginTest.testValidLogin(LoginTest.java:19)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testValidLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.orangehrm.tests.LoginTest@402bba4f]" started-at="2025-03-12T20:05:05 IST" name="tearDown" finished-at="2025-03-12T20:05:06 IST" duration-ms="281" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.orangehrm.tests.LoginTest@402bba4f]" started-at="2025-03-12T20:05:06 IST" name="setUp" finished-at="2025-03-12T20:05:09 IST" duration-ms="3716" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="verifyForgetYourPassword()[pri:0, instance:com.orangehrm.tests.LoginTest@402bba4f]" started-at="2025-03-12T20:05:09 IST" name="verifyForgetYourPassword" finished-at="2025-03-12T20:05:10 IST" duration-ms="600" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyForgetYourPassword -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.orangehrm.tests.LoginTest@402bba4f]" started-at="2025-03-12T20:05:10 IST" name="tearDown" finished-at="2025-03-12T20:05:10 IST" duration-ms="242" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.orangehrm.tests.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
